#!/bin/bash

# Specify the directory where your Python files are located
python_files_directory="/home/vboxuser/Downloads/TrainSim-master/simulation/scripts"

# Specify the target file
target_file="switch.py"

# Use sed to replace port numbers from 12345 to 5002 and 12344 to 5010 in the target file
sed -i 's/\b5002\b/12345/g' "$python_files_directory/$target_file"
sed -i 's/\b5010\b/12344/g' "$python_files_directory/$target_file"
